def CLIENT_ID():
    CLIENT_ID = 'YOUR_CLIENT_ID_HERE'
    return CLIENT_ID

def CLIENT_SECRET():
    CLIENT_SECRET = 'YOUR_CLIENT_SECRET_HERE'
    return CLIENT_SECRET

def REDIRECT_URI():
    REDIRECT_URI = 'YOUR_REDIRECT_URI_HERE'
    return REDIRECT_URI
